# Generated by Django 3.1.3 on 2021-02-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_squashed_0002_auto_20210207_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=1, related_name='albums', to='store.Artist'),
        ),
    ]
